name: "Smartmeter Burgenland MQTT"
version: "0.1.6"
slug: "smartmeter_bgld_mqtt"
description: |
  This addon allows you to connect your smartmeter in Burgenland, AT to 
  homeassistant.
url: "https://github.com/r00tat/smartmeter_homeassistant_burgenland"
image: paulwoelfel/smartmeter_homeassistant_burgenland_{arch}
arch:
  - "aarch64"
  - "amd64"
  # works theoretically, but no images have been pushed
  # - "armhf"
  # - "armv7"
  # - "i386"

startup: "application"
boot: "auto"
# host_network: true
# privileged:
#  - "NET_ADMIN"
options:
  mqtt:
    device_id: "smartmeter"
    name: "Smart Meter"
    host: "homeassistant.local"
    port: 1883
    user: ""
    password: ""
    keepalive: 60
    prefix: ""
  dlms:
    port: "/dev/ttyUSB0"
    baudrate: 9600
    bytesize: 8
    # parity: "NONE" # TODO needs to be parsed
    stopbits: 1
    key: "" # hex key to decrypt message
schema:
  mqtt:
    device_id: "str?"
    name: "str?"
    host: "str"
    port: "int?"
    user: "str"
    password: "str"
    keepalive: "int?"
    prefix: "str?"
  dlms:
    port: "str"
    baudrate: "int?"
    bytesize: "int?"
    # parity: "NONE" # TODO needs to be parsed
    stopbits: "int?"
    key: "str" # hex key to decrypt message
map:
  - "share:ro"
  - "config:ro"
devices:
  - /dev/ttyUSB0
  - /dev/ttyUSB1
  - /dev/ttyUSB2
  - /dev/ttyUSB3
usb: true
uart: true
init: false
