name: "Smartmeter Burgenland MQTT"
version: "0.1.2"
slug: "smartmeter_bgld_mqtt"
description: |
  This addon allows you to connect your smartmeter in Burgenland, AT to 
  homeassistant.
url: "https://github.com/r00tat/smartmeter_homeassistant_burgenland"
image: paulwoelfel/smartmeter_homeassistant_burgenland_{arch}
arch: 
  # - "armhf"
  - "armv7"
  - "aarch64"
  # works theoretically, but no images have been pushed
  # - "amd64"
  # - "i386"

startup: "application"
boot: "auto"
# host_network: true
# privileged:
#  - "NET_ADMIN"
options:
  configfile: "/config/smartmeter-config.yaml"
schema:
  configfile: "str"
map:
  - "share:ro"
  - "config:ro"
devices:
  - /dev/ttyUSB0
  - /dev/ttyUSB1
  - /dev/ttyUSB2
  - /dev/ttyUSB3
usb: true
uart: true
init: false
