name: Changelog
on:
  push: {}
  # release:
  #   types:
  #     - created
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: "✏️ Generate release changelog"
        id: changelog
        uses: janheinrichmerker/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "show changelog"
        env:
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
        # working-directory: smartmeter
        run: |
          set -x
          echo "Current changelog:"
          echo "$CHANGELOG"
          ls -lha .
          pwd
          echo "writing log file"
          echo "$CHANGELOG" > smartmeter/CHANGELOG.md
          echo "CHANGELOG updated."

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.ref_name }}
          commit_message: "docs: update CHANGELOG.md for ${{ github.ref_name }}"
          file_pattern: smartmeter/CHANGELOG.md
