name: "Pull Request"

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  pull_request:
    name: "Lint and Test"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4.2.2"

      - name: "Set up Python"
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.12"
          cache: "pip"

      - name: "Install requirements"
        run: |
          python3 -m pip install uv && 
          uv venv &&
          source .venv/bin/activate &&
          uv pip install -r smartmeter/requirements.txt

      - name: "Lint"
        run: |
          source .venv/bin/activate &&
          cd smartmeter &&
          python3 -m ruff check

      # - name: 'Test'
      #   run: |
      #     source .venv/bin/activate &&
      #     python3 -m unittest discover -v
      #   env: # Or as an environment variable
      #     BLAULICHTSMS_CUSTOMERID: '${{ secrets.BLAULICHTSMS_CUSTOMERID }}'
      #     BLAULICHTSMS_USERNAME: '${{ secrets.BLAULICHTSMS_USERNAME }}'
      #     BLAULICHTSMS_PASSWORD: '${{ secrets.BLAULICHTSMS_PASSWORD }}'

      # - name: "Adjust version number"
      #   shell: "bash"
      #   run: |
      #     yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
      #       "${{ github.workspace }}/custom_components/blaulichtsms/manifest.json"

      # - name: "ZIP the integration directory"
      #   shell: "bash"
      #   run: |
      #     cd "${{ github.workspace }}/custom_components/blaulichtsms"
      #     zip hassio_blaulichtsms.zip -r ./

      # - name: "Upload the ZIP file to the release"
      #   uses: softprops/action-gh-release@v0.1.15
      #   with:
      #     files: ${{ github.workspace }}/custom_components/blaulichtsms/hassio_blaulichtsms.zip
