name: "Pull Request"

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  pull_request:
    name: "Lint and Test"
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v6.0.2"

      - name: "Set up Python"
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.13"
          cache: "pip"

      - name: "Install requirements"
        run: |
          python3 -m pip install uv &&
          uv venv &&
          source .venv/bin/activate &&
          uv pip install -r smartmeter/requirements-dev.txt

      - name: "Lint"
        run: |
          source .venv/bin/activate &&
          cd smartmeter &&
          python3 -m ruff check

      - name: "Type check"
        run: |
          source .venv/bin/activate &&
          python3 -m mypy --config-file mypy.ini

      - name: "Test"
        run: |
          source .venv/bin/activate &&
          cd smartmeter &&
          python3 -m pytest tests/ -v


  test-build:
    name: "Test build ${{ matrix.arch }} image"
    needs: pull_request
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            os: ubuntu-24.04
          - arch: aarch64
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v6.0.2"

      - name: "Test build ${{ matrix.arch }} image"
        uses: home-assistant/builder/actions/build-image@2026.03.2
        with:
          arch: ${{ matrix.arch }}
          context: smartmeter
          image: docker.io/paulwoelfel/smartmeter_homeassistant_burgenland_${{ matrix.arch }}
          image-tags: test
          version: test
          container-registry-password: "unused"
          build-args: |
            BUILD_FROM=ghcr.io/hassio-addons/base-python:stable
          push: "false"
          cosign: "false"
