name: "Release"

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  prepare:
    name: "Prepare release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v6.0.2"

      - name: "Adjust version number"
        shell: "bash"
        env:
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          yq -i '.version=strenv(RELEASE_TAG)' \
            "${{ github.workspace }}/smartmeter/config.yaml"

      - name: "✏️ Generate release changelog"
        id: changelog
        uses: janheinrichmerker/action-github-changelog-generator@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "write changelog"
        env:
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
        run: |
          set -x
          echo "writing log file"
          echo "$CHANGELOG" | sed 's@%0A@\n@g' > smartmeter/CHANGELOG.md
          echo "Current changelog:"
          cat smartmeter/CHANGELOG.md
          echo "CHANGELOG updated."

      - name: Commit config.yaml
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: main
          commit_message: "Update version to ${{ github.event.release.tag_name }} and update CHANGELOG.md"
          file_pattern: smartmeter/config.yaml smartmeter/CHANGELOG.md

  build:
    name: "Build ${{ matrix.arch }} image"
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: amd64
            os: ubuntu-24.04
          - arch: aarch64
            os: ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v6.0.2"
        with:
          ref: main

      - name: "Build and publish ${{ matrix.arch }} image"
        uses: home-assistant/builder/actions/build-image@2026.03.2
        with:
          arch: ${{ matrix.arch }}
          context: smartmeter
          image: docker.io/paulwoelfel/smartmeter_homeassistant_burgenland_${{ matrix.arch }}
          image-tags: |
            ${{ github.event.release.tag_name }}
            latest
          version: ${{ github.event.release.tag_name }}
          container-registry: docker.io
          container-registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
          container-registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
          build-args: |
            BUILD_FROM=ghcr.io/hassio-addons/base-python:stable
          push: "true"
          cosign: "false"
